name: Deploy to github pages

#Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    #use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    #uses github's checkout action to checkout code from master branch
    - uses: actions/checkout@v2
    
    #sets up .NET Core SDK 7.0.101 version(the latest)
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: 7.0.101
        
    #publish blazor project to release-folder
    - name: Publish .NET Core Project
      run: dotnet publish -c Release -o release --nologo
      
    #change base tag in index.html from / to sample to match github pages repository subdirectory
    - name: Change base-tag in index.html from / to sample
      run: sed -i 's/<base href="\/" \/>/<base href="\/sample\/" \/>/g' release/wwwroot/index.html
      
    #copy index.html code int0 404.html when file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    
    #add .nojekyll file to tell github that the project is not a jekyll project.
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-actions@4.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
